
insert into address values (1, 'Olmo', 3, 'Zaragoza');
insert into address values (2, 'Pino', 4, 'Madrid');
insert into address values (3, 'Pino', 4, 'Madrid');
insert into address values (4, 'Pino', 4, 'Madrid');
insert into address values (5, 'Pino', 4, 'Madrid');
insert into address values (6, 'Pino', 4, 'Madrid');
insert into address values (7, 'Pino', 4, 'Madrid');
insert into address values (8, 'Pino', 4, 'Madrid');
insert into address values (9, 'Pino', 4, 'Madrid');
insert into address values (10, 'Pino', 4, 'Madrid');
insert into address values (11, 'Pino', 4, 'Madrid');
insert into person values (1, 'John', 'Doe', 1);
insert into person values (2, 'Pepe', 'Luis', 2);
insert into person values (3, 'Pepe 3', 'Luis', 3);
insert into person values (4, 'Pepe 4', 'Luis', 4);
insert into person values (5, 'Pepe 5', 'Luis', 5);
insert into person values (6, 'Pepe 6', 'Luis', 6);
insert into person values (7, 'Pepe 7', 'Luis', 7);
insert into person values (8, 'Pepe 7', 'Luis', 8);
insert into person values (9, 'Pepe 7', 'Luis', 9);
insert into person values (10, 'Pepe 7', 'Luis', 10);
insert into person values (11, 'Pepe 7', 'Luis', 11);
